name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for contributing! Looking forward to interact more :)'' first issue'
        pr-message: 'Thank you for your first PR! That's a valuable help for our project!'' first pr'
